### ISSUE TITLE
Release 0.10

### ISSUE THREAD

**Issue by geppy** [google/uri.dart#21]
0.10 is great!  It enables compatibility with [test](https://github.com/dart-lang/test) 0.12 (that's what I care about, though technically what it does directly is enable compatibility with [matcher](https://github.com/dart-lang/matcher) 0.12).  I've got local patches for a number of other projects (specifically, [shelf_rpc](https://github.com/dart-lang/shelf_rpc), [rpc](https://github.com/dart-lang/rpc), and [shelf_route](https://bitbucket.org/andersmholmgren/shelf_route)) that updates them to not die horribly when used in a project with the latest version of `test`, but they all (directly or indirectly) depend on `uri`.  Would it be possible to release an 0.10 for `uri`?  Thanks!

**Comment by justinfagnani** [comment]
Yep!

**Comment by Fox32** [comment]
I would also look forward to a wider quiver constraint.
