### ISSUE TITLE
Upgrade quiver dependency

### ISSUE THREAD

**Issue by enyo** [google/uri.dart#34]
I think that quiver `^2.0.0` should be used as a dependency now.

**Comment by martflu** [comment]
also `utf` needs to be `^0.9.0+5`

**Comment by buntagonalprism** [comment]
The outdated quiver dependency now causes conflicts with the beta channel of Flutter, namely in the flutter_test package

**Comment by MathieuAuclair** [comment]
I've made a pull request here https://github.com/google/uri.dart/pull/35 and all test are passing, this is solving this issue
