### ISSUE TITLE
Publish with correct version for null safety

### ISSUE THREAD

**Issue by avbk** [google/uri.dart#45]
I just saw that @kevmoo updated this package a couple of days ago and it looks like it has been migrated to be null safe.

Still, in my project I am told, that the current version is not nullsafe:

```
$ flutter --version
Flutter 1.26.0-17.5.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 1fe38dcb5f (2 days ago) • 2021-02-10 16:25:47 -0800
Engine • revision d4453f6018
Tools • Dart 2.12.0 (build 2.12.0-259.9.beta)

$ dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name   Current  Upgradable  Resolvable  Latest   

direct dependencies:
uri            ✗0.11.4  -           -           ✗0.11.4  
```

According to the [publish step](https://dart.dev/null-safety/migration-guide#step5-publish) in the migration guide the version must be different:
> Update the version of the package to indicate a breaking change and include a nullsafety suffix:
>
>   If your package is already at 1.0.0 or greater, increase the major version. For example, if the previous version is 2.3.2, the new version is 3.0.0-nullsafety.0.
>
>    If your package hasn’t reached 1.0.0 yet, either increase the minor version or update the version to 1.0.0. For example, if the previous version is 0.3.2, the new version is one of the following:
>        0.4.0-nullsafety.0
>        1.0.0-nullsafety.0
>
> For subsequent updates to the null-safe prerelease of the package, increment the prerelease suffix. For example, if the first null-safe version is 3.0.0-nullsafety.0, then the next one is 3.0.0-nullsafety.1.
> [...]

So I guess someone needs to publish this at least as `0.12.0-nullsafefy.0` or as `1.0.0-nullsafety.0` as this is already been written in the `pubspec.yaml`.

**Comment by bsutton** [comment]
Looks like the pubspec has 1.0.0-nullsafety.0 but we need this published as its blocking several projects I'm reliant on including pubspec.

@kevmoo  can we get this published please.

**Comment by kevmoo** [comment]
Just published!

**Comment by bsutton** [comment]
thank you very much!!!

**Comment by avbk** [comment]
Thanks!
